parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Shared\:
        resource: '../src/Shared/*'
        autowire: true
        autoconfigure: true

imports:
    - { resource: 'module/*/*.yaml' }
